// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9BS9dMsQZnytwiQ_Pu7NiQJ9YvMidbU',
    appId: '1:486551413291:web:32bca2fc074b4ea42ec06e',
    messagingSenderId: '486551413291',
    projectId: 'chatapp-4da6e',
    authDomain: 'chatapp-4da6e.firebaseapp.com',
    storageBucket: 'chatapp-4da6e.firebasestorage.app',
    measurementId: 'G-S31BVWG5VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYb4hkId-CHweWM1xP90WFWhXeTPYLdQI',
    appId: '1:486551413291:android:836d6329db693b6c2ec06e',
    messagingSenderId: '486551413291',
    projectId: 'chatapp-4da6e',
    storageBucket: 'chatapp-4da6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQao8G7KXL7tPTk_aNBXsnZ4L-xD4q9no',
    appId: '1:486551413291:ios:649c4ccb72c4ecb12ec06e',
    messagingSenderId: '486551413291',
    projectId: 'chatapp-4da6e',
    storageBucket: 'chatapp-4da6e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQao8G7KXL7tPTk_aNBXsnZ4L-xD4q9no',
    appId: '1:486551413291:ios:649c4ccb72c4ecb12ec06e',
    messagingSenderId: '486551413291',
    projectId: 'chatapp-4da6e',
    storageBucket: 'chatapp-4da6e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9BS9dMsQZnytwiQ_Pu7NiQJ9YvMidbU',
    appId: '1:486551413291:web:b774264313b2a0be2ec06e',
    messagingSenderId: '486551413291',
    projectId: 'chatapp-4da6e',
    authDomain: 'chatapp-4da6e.firebaseapp.com',
    storageBucket: 'chatapp-4da6e.firebasestorage.app',
    measurementId: 'G-RSJTK9DHGC',
  );
}
